### PR TITLE
Release notes for Android Core 1.11.5

### PR DESCRIPTION
**Pull request by yangyansong-adbe**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by calebk1 — APPROVED** [review]
LGTM!

**Comment by praveek** [comment]
This should go in the https://github.com/AdobeDocs/acp-mobile-sdkdocs repo.

**Review by praveek — CHANGES_REQUESTED** [review]
This should go in the [AdobeDocs/acp-mobile-sdkdocs](https://github.com/AdobeDocs/acp-mobile-sdkdocs) repo.

**Comment by yangyansong-adbe** [comment]
@calebk1  @praveek  created a new PR in ACP repo https://github.com/AdobeDocs/acp-mobile-sdkdocs/pull/57

**Pull request closed without merging**
