### PR TITLE
Fix tabs and tags issues within AJO in-app docs

### PR DESCRIPTION
**Pull request by rymorale**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by calebk1 — APPROVED** [review]
LGTM!

I'm assuming these changes were tested on localhost?

**Review by calebk1 — CHANGES_REQUESTED** [review]
(Changing this to request changes until I get confirmation that it's been localhost tested.)

**Comment by calebk1** [comment]
Also to double check - is this supposed to go to main?

**Comment by rymorale** [comment]
i have verified that the tabs look correct when locally hosting the docs.

**Comment by calebk1** [comment]
@rymorale Just to confirm - this is meant to be merged into main?

**Comment by rymorale** [comment]
@calebk1 yes as these changes are in the main branch already. i talked to @swarna04 about this and we will merge the same changes to staging to help prevent conflicts.

**Review by calebk1 — APPROVED** [review]

**Pull request merged**
