### PR TITLE
Update release notes for Android Campaign Standard 1.0.10

### PR DESCRIPTION
**Pull request by rymorale**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by swarna04** [comment]
@rymorale Please create this pr against the https://github.com/AdobeDocs/acp-mobile-sdkdocs repo. This repo will contain ACS latest 2.x docs/ release notes/ APIs.

**Review by calebk1 — APPROVED** [review]
LGTM!

**Comment by rymorale** [comment]
> @rymorale Please create this pr against the https://github.com/AdobeDocs/acp-mobile-sdkdocs repo. This repo will contain ACS latest 2.x docs/ release notes/ APIs.
I see, thanks for the heads up.

**Comment by rymorale** [comment]
Closing this pr and will open one against the ACP doc repo.

**Pull request closed without merging**
